name: FFHack Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        run: |
          clang++ -arch arm64 -dynamiclib -O2 -mios-version-min=15.0 -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -framework Foundation -framework CoreFoundation -framework UIKit -o FFHack.dylib FFHack.mm
          ls -la FFHack.dylib
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: FFHack
          path: FFHack.dylib
